apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: helm-aws-cert-manager
  annotations:
    meta.crossplane.io/maintainer: Patrick Lee Scott
    meta.crossplane.io/source: github.com/hops-ops/helm-aws-cert-manager
    meta.crossplane.io/description: Installs cert-manager with AWS Pod Identity for Route53 DNS01 challenges.
spec:
  dependsOn:
  - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: ">=v0.6.0"
  - configuration: ghcr.io/hops-ops/helm-cert-manager
    version: ">=v0.5.0"
  - configuration: ghcr.io/hops-ops/aws-pod-identity
    version: ">=v0.4.1"
